### ISSUE TITLE
No list of Command Aliases

### ISSUE THREAD

**Issue by smonheim** [brian91292/EnhancedStreamChat#15]
There's no easy way to find the available commands for chat parsing.

add, bsr, and request are default shown, but nothing is default or easily seen to be for showing the current queue.

**Comment by brian91292** [comment]
Started collaborating with @angturil on this today; he's actually already got this implemented and we're working on getting everything merged now.

You can view the progress here:
https://github.com/brian91292/BeatSaber-EnhancedTwitchChat/tree/angturil-fork-merge

Hopefully should be have something ready for release within the next week or two.

**Comment by brian91292** [comment]
If you still have an issue with this make sure to report it over on angturils github:
https://github.com/angturil/SongRequestManager
