### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by KorayZ** [brian91292/EnhancedStreamChat#40]
Hi, I was sent here by the support channel. My game crashes whenever songrequestmanger, enhanched chat, and streamcore is installed. 
![image](https://user-images.githubusercontent.com/39472736/55766251-d2f29c80-5a41-11e9-8ba8-641e2d8110cc.png)

**Comment by brian91292** [comment]
Rerun the mod installer? Not sure what to suggest, really nothing to go off here. Chances are you failed to install it properly, though.

**Comment by brian91292** [comment]
After you have rerun the mod installer, if the issue persists post your output_log.txt file from `%appdata%\..\LocalLow\Hyperbolic Magnetism\Beat Saber` for me to examine.
