### ISSUE TITLE
v13 Does Not Show Sub Icons and Badges

### ISSUE THREAD

**Issue by stormtrooper298** [brian91292/EnhancedStreamChat#41]
As the title states, v12 of enhancedtwitchchat showed sub badges and icons next to their names, but suddenly on v13 of the mod, it does not.

Was this removed on purpose? If not, can we implement this back into v13 please?

Thank you a bunch for all of your hard work on this mod, it is greatly appreciated.

**Comment by brian91292** [comment]
This issue is fixed in the latest version of the mod.
