### ISSUE TITLE
Just showing 1 line with lock

### ISSUE THREAD

**Issue by the7goonies** [brian91292/EnhancedStreamChat#46]
Hello! I've looked through your closed issues and only found one thread similar to my issue, however that was almost a year ago. I'm having issues getting twitch chat to appear using the Enhanced Stream Chat plugin in ModAssistant.. I've added the username, OAuth key, and even the commands work in twitch chat from the computer.. but all I still get is a window with the lock. Any help is appreciated
![image](https://user-images.githubusercontent.com/54484779/63642543-ba042400-c68e-11e9-805c-92857de5f8fe.png)

**Comment by Sayrer0** [comment]
Did you fixed it?

**Comment by brian91292** [comment]
If you want to share a log file with me from a session where this happened I'll look into it. I haven't had this happen to me in quite a long time so I'm not sure what might be causing it for you.
